============================= test session starts ==============================
platform darwin -- Python 3.13.3, pytest-8.3.5, pluggy-1.6.0
django: version: 5.2.1, settings: es_app.settings (from option)
rootdir: /Users/hoshimotoyasunori/Desktop/project/app/backend
plugins: django-4.11.1
collected 90 items

api/tests.py .....................................F........F............ [ 65%]
...............................                                          [100%]

=================================== FAILURES ===================================
__________ APISmokeTest.test_reportrecord_search_negotiation_content ___________
api/tests.py:621: in test_reportrecord_search_negotiation_content
    self.assertIn('検索商談', response.content.decode())
E   AssertionError: '検索商談' not found in '{"count":0,"next":null,"previous":null,"results":[]}'
________________ APISmokeTest.test_surveyrecord_search_summary _________________
api/tests.py:616: in test_surveyrecord_search_summary
    self.assertIn('検索概要', response.content.decode())
E   AssertionError: '検索概要' not found in '{"count":0,"next":null,"previous":null,"results":[]}'
=========================== short test summary info ============================
FAILED api/tests.py::APISmokeTest::test_reportrecord_search_negotiation_content
FAILED api/tests.py::APISmokeTest::test_surveyrecord_search_summary - Asserti...
================== 2 failed, 88 passed, 13 warnings in 19.87s ==================
